In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

sentiment                                            message  tweetid
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221
1          1  It's not like we lack evidence of anthropogeni...   126103
2          2  RT @RawStory: Researchers say we have three ye...   698562
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954

In [4]:
##counting each sentiment
df['sentiment'].value_counts()

 1    8530
 2    3640
 0    2353
-1    1296
Name: sentiment, dtype: int64

In [5]:
##checking null values
df.isnull().sum()

sentiment    0
message      0
tweetid      0
dtype: int64

In [6]:
list(df.itertuples())

[Pandas(Index=0, sentiment=1, message="PolySciMajor EPA chief doesn't think carbon dioxide is main cause of global warming and.. wait, what!? https://t.co/yeLvcEFXkC via @mashable", tweetid=625221),
 Pandas(Index=1, sentiment=1, message="It's not like we lack evidence of anthropogenic global warming", tweetid=126103),
 Pandas(Index=2, sentiment=2, message='RT @RawStory: Researchers say we have three years to act on climate change before it’s too late https://t.co/WdT0KdUr2f https://t.co/Z0ANPT…', tweetid=698562),
 Pandas(Index=3, sentiment=1, message='#TodayinMaker# WIRED : 2016 was a pivotal year in the war on climate change https://t.co/44wOTxTLcD', tweetid=573736),
 Pandas(Index=4, sentiment=1, message="RT @SoyNovioDeTodas: It's 2016, and a racist, sexist, climate change denying bigot is leading in the polls. #ElectionNight", tweetid=466954),
 Pandas(Index=5, sentiment=1, message="Worth a read whether you do or don't believe in climate change https://t.co/ggLZVNYjun https://t.co/7AF

In [7]:
##checking blank messages
blank_index = [i[0] for i in df.itertuples() if i[2].isspace()]
blank_index

[]

In [8]:
##removing links
import re

In [9]:
def remove_links(df,col):
    df['new_message'] = df[col].apply(lambda s: re.sub(r"http\S+", "", s))
    return df

In [10]:
df = remove_links(df,'message').copy()

In [11]:
df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

                                         new_message  
0  PolySciMajor EPA chief doesn't think carbon di...  
1  It's not like we lack evidence of anthropogeni...  
2  RT @RawStory: Researchers say we have three ye...  
3  #TodayinMaker# WIRED : 2016 was a pivotal year...  
4  RT @SoyNovioDeTodas: It's 2016, and a racist, ...

In [12]:
##removing elements preceeded by @ or #
def remove_word(df,col):
    df['no_@_#'] = df[col].apply(lambda s: re.sub(r"@\S+|#\S+", "", s))
    return df

In [13]:
df = remove_word(df,'new_message')

In [14]:
df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

                                         new_message  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT @RawStory: Researchers say we have three ye...   
3  #TodayinMaker# WIRED : 2016 was a pivotal year...   
4  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   

                                              no_@_#  
0  PolySciMajor EPA chief doesn't think carbon di...  
1  It's not like we lack evidence of anthropogeni...  
2  RT  Researchers say we have three years to act...  
3   WIRED : 2016 was a pivotal year in the war on...  
4  RT  It's 2016, and a racist, sexist, climate c...

In [15]:
##removing puntuations except (')
def remove_punc(df,col):
    df['n_punc'] = df[col].apply(lambda s:''.join(i for i in s if i not in '!"#$%&\()*+,-./:;<=>?@[\\]^_`{|}~'))
    return df

In [16]:
df = remove_punc(df,'no_@_#')

In [17]:
df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

                                         new_message  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT @RawStory: Researchers say we have three ye...   
3  #TodayinMaker# WIRED : 2016 was a pivotal year...   
4  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   

                                              no_@_#  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT  Researchers say we have three years to act...   
3   WIRED : 2016 was a pivotal year in the war on...   
4  RT  It's 2016, and a racist, sexist, climate c...   

                                              n_punc  
0  PolySciMajor EPA chief doesn't think carbon di...  
1  It's not like we lack evidence of anthropogeni...  
2  RT  Researchers say we have three years to act...  
3   WIRED  2016 was a pivotal year in the war on ...  
4  RT  It's 2016 and a racist sexist climate chan...

In [18]:
##removing entities
import spacy
nlp = spacy.load('en_core_web_lg')


In [19]:
def remove_enties(string):
    doc = nlp(string)
    no_entities = []
    entitis = [e.text for e in doc.ents]
    for t in doc:
        if t.text in entitis:
            pass
        else:
            no_entities.append(t.text)
    return ' '.join(no_entities)

In [20]:
print(remove_enties('This is a text document that speaks about entities like Sweden and Nokia'))

This is a text document that speaks about entities like and


In [21]:
df['no_enties'] = df['n_punc'].apply(remove_enties)

In [22]:
df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

                                         new_message  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT @RawStory: Researchers say we have three ye...   
3  #TodayinMaker# WIRED : 2016 was a pivotal year...   
4  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   

                                              no_@_#  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT  Researchers say we have three years to act...   
3   WIRED : 2016 was a pivotal year in the war on...   
4  RT  It's 2016, and a racist, sexist, climate c...   

                                              n_punc  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT  Researchers say we have three years to act...   
3   WIRED  2016 was a pivotal year in the war on ...   
4  RT  It's 2016 and a racist sexist climate chan...   

                                           no_enties  
0  PolySciMajor chief does n't think carbon dioxi...  
1  It 's not like we lack evidence of anthropogen...  
2    Researchers say we have three years to act o...  
3    WIRED   was a pivotal year in the war on cli...  
4  RT   It 's and a racist sexist climate change ...

In [23]:
##removing numbers
def remove_numbers(df,col):
    df['no_numbers'] = df[col].apply(lambda s:''.join(i for i in s if i not in '0123456789'))
    return df

In [24]:
df = remove_numbers(df,'no_enties')

In [25]:
df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

                                         new_message  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT @RawStory: Researchers say we have three ye...   
3  #TodayinMaker# WIRED : 2016 was a pivotal year...   
4  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   

                                              no_@_#  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT  Researchers say we have three years to act...   
3   WIRED : 2016 was a pivotal year in the war on...   
4  RT  It's 2016, and a racist, sexist, climate c...   

                                              n_punc  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT  Researchers say we have three years to act...   
3   WIRED  2016 was a pivotal year in the war on ...   
4  RT  It's 2016 and a racist sexist climate chan...   

                                           no_enties  \
0  PolySciMajor chief does n't think carbon dioxi...   
1  It 's not like we lack evidence of anthropogen...   
2    Researchers say we have three years to act o...   
3    WIRED   was a pivotal year in the war on cli...   
4  RT   It 's and a racist sexist climate change ...   

                                          no_numbers  
0  PolySciMajor chief does n't think carbon dioxi...  
1  It 's not like we lack evidence of anthropogen...  
2    Researchers say we have three years to act o...  
3    WIRED   was a pivotal year in the war on cli...  
4  RT   It 's and a racist sexist climate change ...

In [64]:
##removing imojis
def deEmojify(inputString):
    return inputString.encode('ascii', 'ignore').decode('ascii')

In [65]:
df['no_imojis'] = df['no_numbers'].apply(deEmojify)

In [66]:
df.head()

sentiment                                            message  tweetid  \
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221   
1          1  It's not like we lack evidence of anthropogeni...   126103   
2          2  RT @RawStory: Researchers say we have three ye...   698562   
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736   
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954   

                                         new_message  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT @RawStory: Researchers say we have three ye...   
3  #TodayinMaker# WIRED : 2016 was a pivotal year...   
4  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   

                                              no_@_#  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT  Researchers say we have three years to act...   
3   WIRED : 2016 was a pivotal year in the war on...   
4  RT  It's 2016, and a racist, sexist, climate c...   

                                              n_punc  \
0  PolySciMajor EPA chief doesn't think carbon di...   
1  It's not like we lack evidence of anthropogeni...   
2  RT  Researchers say we have three years to act...   
3   WIRED  2016 was a pivotal year in the war on ...   
4  RT  It's 2016 and a racist sexist climate chan...   

                                           no_enties  \
0  PolySciMajor chief does n't think carbon dioxi...   
1  It 's not like we lack evidence of anthropogen...   
2    Researchers say we have three years to act o...   
3    WIRED   was a pivotal year in the war on cli...   
4  RT   It 's and a racist sexist climate change ...   

                                          no_numbers  \
0  PolySciMajor chief does n't think carbon dioxi...   
1  It 's not like we lack evidence of anthropogen...   
2    Researchers say we have three years to act o...   
3    WIRED   was a pivotal year in the war on cli...   
4  RT   It 's and a racist sexist climate change ...   

                                           no_imojis  
0  PolySciMajor chief does n't think carbon dioxi...  
1  It 's not like we lack evidence of anthropogen...  
2    Researchers say we have three years to act o...  
3    WIRED   was a pivotal year in the war on cli...  
4  RT   It 's and a racist sexist climate change ...

In [67]:
##data splitting
from sklearn.model_selection import train_test_split
X = df['no_imojis']
y = df['sentiment']

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [69]:
##importing models
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC,SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score

In [70]:
##creating a pipeline for each model
txt1_clf = Pipeline([('vectorizer',TfidfVectorizer(stop_words='english',strip_accents='ascii')),('clf',LinearSVC())])
txt2_clf = Pipeline([('vectorizer',TfidfVectorizer(stop_words='english',strip_accents='ascii')),('clf',MultinomialNB())])
txt3_clf = Pipeline([('vectorizer',TfidfVectorizer(stop_words='english',strip_accents='ascii')),('clf',RandomForestClassifier(n_estimators=100))])
txt4_clf = Pipeline([('vectorizer',TfidfVectorizer(stop_words='english',strip_accents='ascii')),('clf',SVC(C=1.0,probability=True))])

In [71]:
##training all the models
def fit_all(lst,X,y):
    lis = []
    for pip in lst:
        pip.fit(X,y)
        lis.append(pip)
    return lis

In [72]:
trained=fit_all([txt1_clf,txt2_clf,txt3_clf,txt4_clf],X=X_train,y=y_train)

C:\Users\1437795\AppData\Local\Continuum\anaconda3\envs\nlp_course\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [73]:
trained

[Pipeline(memory=None,
      steps=[('vectorizer', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
         dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
         lowercase=True, max_df=1.0, max_features=None, min_df=1,
         ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=...ax_iter=1000,
      multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
      verbose=0))]),
 Pipeline(memory=None,
      steps=[('vectorizer', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
         dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
         lowercase=True, max_df=1.0, max_features=None, min_df=1,
         ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=...rue,
         vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]),
 Pipeline(memory=None,
      steps=[('vectorizer', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',


In [74]:
##making predictions for each trained model

##LinearSV
pip1_prediction = trained[0].predict(X_test)
##Naive
pip2_prediction = trained[1].predict(X_test)
##Random forest
pip3_prediction = trained[2].predict(X_test)
##SVC
pip4_prediction = trained[3].predict(X_test)

In [75]:
##evaluation of the models

print('LinearSV')
print(classification_report(y_test,pip1_prediction))
print('\n\n')
print('Naive')
print(classification_report(y_test,pip2_prediction))
print('\n\n')
print('Random forest')
print(classification_report(y_test,pip3_prediction))
print('\n\n')
print('SVC')
print(classification_report(y_test,pip4_prediction))

LinearSV
              precision    recall  f1-score   support

          -1       0.68      0.38      0.48       428
           0       0.52      0.43      0.47       737
           1       0.73      0.82      0.78      2861
           2       0.69      0.68      0.69      1195

   micro avg       0.70      0.70      0.70      5221
   macro avg       0.66      0.58      0.60      5221
weighted avg       0.69      0.70      0.69      5221




Naive
              precision    recall  f1-score   support

          -1       1.00      0.02      0.04       428
           0       0.91      0.08      0.15       737
           1       0.61      0.98      0.75      2861
           2       0.84      0.41      0.55      1195

   micro avg       0.64      0.64      0.64      5221
   macro avg       0.84      0.37      0.37      5221
weighted avg       0.74      0.64      0.56      5221




Random forest
              precision    recall  f1-score   support

          -1       0.77      0.19      0

C:\Users\1437795\AppData\Local\Continuum\anaconda3\envs\nlp_course\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [76]:
##testing Accuracy score
print('LinearSV')
print(accuracy_score(y_test,pip1_prediction))
print('\n\n')
print('Naive')
print(accuracy_score(y_test,pip2_prediction))
print('\n\n')
print('Random forest')
print(accuracy_score(y_test,pip3_prediction))

LinearSV
0.6975675158015706



Naive
0.6410649300900211



Random forest
0.6755410840835089


In [77]:
##LSTM implementation
max_no_words = 50000
max_sequence = 250
embedding = 100

In [78]:
from keras.preprocessing.text import Tokenizer

In [79]:
tokenizer = Tokenizer(num_words=max_no_words)

In [80]:
tokenizer.fit_on_texts(df['no_imojis'].values)

In [81]:
word_index  = tokenizer.word_index

In [82]:
word_index

{'climate': 1,
 'change': 2,
 'the': 3,
 'to': 4,
 'is': 5,
 'of': 6,
 'a': 7,
 'rt': 8,
 'global': 9,
 'in': 10,
 "'": 11,
 'warming': 12,
 "'s": 13,
 'and': 14,
 'on': 15,
 'for': 16,
 "n't": 17,
 'it': 18,
 'about': 19,
 'we': 20,
 'that': 21,
 'i': 22,
 'you': 23,
 'are': 24,
 'believe': 25,
 'how': 26,
 'this': 27,
 'not': 28,
 'do': 29,
 'by': 30,
 'have': 31,
 'does': 32,
 'will': 33,
 'be': 34,
 'with': 35,
 'amp': 36,
 'from': 37,
 'if': 38,
 'who': 39,
 'as': 40,
 'trump': 41,
 'but': 42,
 'your': 43,
 'at': 44,
 'world': 45,
 'real': 46,
 'she': 47,
 'what': 48,
 'going': 49,
 'all': 50,
 'he': 51,
 'can': 52,
 'people': 53,
 'just': 54,
 'because': 55,
 'more': 56,
 'our': 57,
 'via': 58,
 'has': 59,
 'new': 60,
 's': 61,
 'so': 62,
 'no': 63,
 'they': 64,
 'an': 65,
 'now': 66,
 'fight': 67,
 'like': 68,
 'was': 69,
 'hoax': 70,
 'says': 71,
 'there': 72,
 'die': 73,
 'scientists': 74,
 'science': 75,
 'why': 76,
 'us': 77,
 'up': 78,
 'when': 79,
 'over': 80,
 'say': 81,


In [83]:
len(word_index)

14001

In [88]:
X = tokenizer.texts_to_sequences(df['no_imojis'].values)

In [89]:
from keras.preprocessing.sequence import pad_sequences

In [90]:
X = pad_sequences(X,maxlen=max_sequence)

In [91]:
type(X)

numpy.ndarray

In [92]:
from keras.utils import to_categorical

In [93]:
y = to_categorical(y,num_classes=4)

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,
                                                    random_state=42)

In [95]:
y.shape

(15819, 4)

In [96]:
from keras import Sequential
from keras.layers import Embedding,SpatialDropout1D,LSTM,Dense

In [97]:
from keras.callbacks import EarlyStopping

In [98]:
model = Sequential()

In [99]:
model.add(Embedding(max_no_words,embedding,input_length=X.shape[1]))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(4,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',
              metrics=['accuracy'])

In [100]:
model.fit(X_train,y_train,epochs=5,batch_size=50,
callbacks=[EarlyStopping(monitor='val_loss', patience=3, min_delta=0.0001)],
verbose=1,validation_split=0.1)


Train on 11389 samples, validate on 1266 samples
Epoch 1/5
11389/11389 [==============================] - 108s 9ms/step - loss: 0.9934 - accuracy: 0.6074 - val_loss: 0.7768 - val_accuracy: 0.6935
Epoch 2/5
11389/11389 [==============================] - 107s 9ms/step - loss: 0.6918 - accuracy: 0.7276 - val_loss: 0.6884 - val_accuracy: 0.7362
Epoch 3/5
11389/11389 [==============================] - 101s 9ms/step - loss: 0.5110 - accuracy: 0.8099 - val_loss: 0.7358 - val_accuracy: 0.7267
Epoch 4/5
11389/11389 [==============================] - 105s 9ms/step - loss: 0.3741 - accuracy: 0.8624 - val_loss: 0.7399 - val_accuracy: 0.7417
Epoch 5/5
11389/11389 [==============================] - 110s 10ms/step - loss: 0.2800 - accuracy: 0.9003 - val_loss: 0.8041 - val_accuracy: 0.7346


In [101]:
y_pre=model.predict(X_test)

In [102]:
y_pre=y_pre.argmax(axis=1)

In [103]:
print(y_pre)

[1 2 1 ... 2 1 2]


In [104]:
y_test=y_test.argmax(axis=1)

In [105]:
y_test

array([1, 2, 1, ..., 2, 1, 3], dtype=int64)

In [106]:
from sklearn.metrics import classification,confusion_matrix,accuracy_score

In [107]:
print(confusion_matrix(y_test,y_pre))

[[ 226  155   28   16]
 [ 159 1429  130   37]
 [  44  153  504    5]
 [  66   94    8  110]]


In [108]:
print(classification_report(y_test,y_pre,target_names=['-1','0','1','2']))

              precision    recall  f1-score   support

          -1       0.46      0.53      0.49       425
           0       0.78      0.81      0.80      1755
           1       0.75      0.71      0.73       706
           2       0.65      0.40      0.49       278

   micro avg       0.72      0.72      0.72      3164
   macro avg       0.66      0.61      0.63      3164
weighted avg       0.72      0.72      0.71      3164



In [ ]:
print(accuracy_score(y_test,y_pre))